Data Analysis of [luis-1-step-like](../../data/luis-1-step-like)
========================================================

## Read Data
```{r ReadData, cache=TRUE}
# Read data of which users like what media.
likes <- read.csv("../../data/luis-1-step-like")
```

## Check Duplication
```{r CheckDuplication, eval=TRUE}
# 0 means no duplication; otherwise duplication exists.
anyDuplicated(likes)
```

## General Information
```{r GeneralInformation}
# Number of likes
num_likes <- nrow(likes)
num_likes
# Number of unique users
num_users <- length(unique(likes$user))
num_users
# Number of unique media
num_media <- length(unique(likes$medium))
num_media
# Sparsity of the utility matrix (% of known entries)
(num_likes / num_users / num_media) * 100
```

## Analyze Like Distribution
### User-Based
```{r UserLikeDistribution, tidy=FALSE, eval=TRUE, fig.width=15}
# Count number of likes for each user.
user_like_count <- data.frame(table(likes$user))$Freq
# Display summary of number of likes for each user.
summary(user_like_count)
# Only includes counts > 20 to make histogram concise.
user_like_count_lt20 <- user_like_count[user_like_count < 20]
# Get histogram object.
h <- hist(user_like_count_lt20,
          breaks=seq(0, 20),
          plot=FALSE)

# Change density to percentage.
h$density <- (h$counts / num_users) * 100

# Plot histogram (with counts on top of bars).
plot(h, freq=FALSE, labels=paste(h$counts),
     main="Histogram of user_like_count < 20",
     xlab="Number of likes",
     ylab="Percentage of users (%)")
# Plot number of user's likes.
plot(sort(user_like_count, decreasing=TRUE),
     main="Number of user's likes",
     xlab="User index",
     ylab="Number of likes")
```

### Medium-Based
```{r MediumLikeDistribution, tidy=FALSE, eval=TRUE}
# Count number of likes for each medium.
medium_like_count <- data.frame(table(likes$medium))$Freq

# Display summary of number of likes for each medium.
summary(medium_like_count)
# Get histogram object.
h <- hist(medium_like_count,
          plot=FALSE)

# Change density to percentage.
h$density <- (h$counts / num_media) * 100

# Plot histogram (with counts on top of bars).
plot(h, freq=FALSE, labels=paste(h$counts),
     xlab="Number of likes",
     ylab="Percentage of media (%)")
# Plot number of medium's likes
plot(sort(medium_like_count, decreasing=TRUE),
     main="Number of medium's likes",
     xlab="Medium index",
     ylab="Number of likes")
```